import { PERMISSIONS, type Permission } from '../auth/permissions';
import { API_SCOPES } from './api-scopes';

export const PERMISSION_TO_API_SCOPE: Partial<Record<Permission, string>> = {
  [PERMISSIONS.SESSIONS_READ]: API_SCOPES.SESSIONS_READ,
  [PERMISSIONS.MESSAGES_READ]: API_SCOPES.MESSAGES_READ,
  [PERMISSIONS.MESSAGES_SEND]: API_SCOPES.MESSAGES_SEND,
  [PERMISSIONS.CONTACTS_READ]: API_SCOPES.CONTACTS_READ,
  [PERMISSIONS.CHATS_READ]: API_SCOPES.CHATS_READ,
  [PERMISSIONS.GROUPS_READ]: API_SCOPES.GROUPS_READ,
  [PERMISSIONS.WEBHOOKS_READ]: API_SCOPES.WEBHOOKS_READ,
};
