packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@whiskeysockets/baileys': true
  protobufjs: true
  msgpackr-extract: true
  puppeteer: true

overrides:
  'whatsapp-web.js>puppeteer': 25.12.0
