'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { api } from '../../../lib/api';
import { Brand } from '../../../components/relay-workspace';

export default function PlatformMfaPage() {
  const router=useRouter();
  const [ticket,setTicket]=useState('');
  const [code,setCode]=useState('');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);

  useEffect(()=>{
    const stored=sessionStorage.getItem('relaywa_platform_mfa_ticket')??'';
    setTicket(stored);
    if(!stored) router.replace('/platform/login');
  },[router]);

  async function submit(event:FormEvent) {
    event.preventDefault();
    if(!ticket)return;
    setBusy(true);setError('');
    try {
      const result=await api<any>('/auth/mfa/verify',undefined,{
        method:'POST',body:JSON.stringify({ticket,code:code.trim()}),
      });
      if(!result.accessToken)throw new Error('MFA challenge was not completed');
      sessionStorage.removeItem('relaywa_platform_mfa_ticket');
      localStorage.setItem('relaywa_access_token',result.accessToken);
      router.replace('/platform');
    } catch(err) {
      setError(err instanceof Error?err.message:'Verification failed. Check your code.');
    } finally {setBusy(false);}
  }

  return <main className="split-login-shell platform-login-shell">
    <section className="split-login-brand">
      <Brand/>
      <div>
        <span className="public-kicker">Additional verification</span>
        <h1>Keep your RelayWA platform secure.</h1>
        <p>Enter the six-digit code generated by your authenticator app, or one of your single-use recovery codes.</p>
      </div>
    </section>
    <section className="split-login-panel">
      <form className="light-auth-card" onSubmit={submit}>
        <p className="eyebrow">Platform administrator · MFA</p>
        <h2>Verify your identity</h2>
        <label>Authenticator or recovery code
          <input value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code"
            required minLength={6} maxLength={32} placeholder="123456" aria-label="Authenticator code"/>
        </label>
        {error&&<div className="alert" role="alert">{error}</div>}
        <button className="primary-button wide" disabled={busy||!ticket}>{busy?'Verifying…':'Verify and continue'}</button>
        <Link href="/platform/login" className="auth-back-link" onClick={()=>sessionStorage.removeItem('relaywa_platform_mfa_ticket')}>Back to sign in</Link>
      </form>
    </section>
  </main>;
}
