'use client';
export type Invoice={number:string;paymentId:string;demo:boolean;status:string;issuedAt:string;organizationName:string;planName:string;billingInterval:string;totalCents:number;currency:string};
export default function DemoInvoice({invoice}:{invoice:Invoice}){
 const amount=new Intl.NumberFormat('en-US',{style:'currency',currency:invoice.currency}).format(invoice.totalCents/100);
 const issued=new Date(invoice.issuedAt).toLocaleDateString();
 function download(){
  const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>${escape(invoice.number)}</title><style>body{font:16px/1.7 Arial;max-width:760px;margin:60px auto;padding:24px;color:#142019}header{border-bottom:2px solid #25d366;padding-bottom:20px}table{width:100%;border-collapse:collapse;margin:30px 0}td,th{padding:14px;text-align:left;border-bottom:1px solid #ddd}small{color:#647569}</style></head><body><header><h1>RelayWA · ${invoice.demo?'Demo invoice':'Invoice'}</h1><p>${escape(invoice.number)}</p></header><p>Billed to: ${escape(invoice.organizationName)}<br>Issued: ${escape(issued)}<br>Status: ${escape(invoice.status)}</p><table><tr><th>Description</th><th>Total</th></tr><tr><td>${escape(invoice.planName)} · ${escape(invoice.billingInterval)} subscription</td><td>${escape(amount)}</td></tr></table><h2>Total: ${escape(amount)}</h2>${invoice.demo?'<small>Simulated payment. No funds collected. This invoice confirms demo subscription activation.</small>':''}</body></html>`;
  const url=URL.createObjectURL(new Blob([html],{type:'text/html'}));const link=document.createElement('a');link.href=url;link.download=invoice.number+'.html';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 return <div className="rw-invoice"><div className="rw-invoice-heading"><strong>RelayWA</strong><span>{invoice.demo?'Demo invoice':'Invoice'} · {invoice.status}</span></div><code>{invoice.number}</code><div className="rw-invoice-meta"><span>Billed to<strong>{invoice.organizationName}</strong></span><span>Issued<strong>{issued}</strong></span></div><div className="rw-invoice-line"><span>{invoice.planName}<small>{invoice.billingInterval} subscription</small></span><strong>{amount}</strong></div><div className="rw-invoice-total"><span>Total</span><strong>{amount}</strong></div>{invoice.demo&&<p>Simulated payment · No funds collected. Your selected plan is active.</p>}<button type="button" className="rw-button secondary" onClick={download}>Download invoice</button></div>;
}
