'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import DemoInvoice from './demo-invoice';
import {api} from '../lib/api';
import {Brand,type Plan} from './relay-workspace';
import {FeatherIcon} from './feather-icon';
export default function DemoCheckout(){
 const [plan,setPlan]=useState<Plan>();const [annual,setAnnual]=useState(false);const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [receipt,setReceipt]=useState<any>();
 useEffect(()=>{const query=new URLSearchParams(window.location.search);setAnnual(query.get('interval')==='annual');setToken(localStorage.getItem('relaywa_access_token')||'');void api<Plan[]>('/public/plans').then(plans=>{const found=plans.find(p=>p.code===query.get('plan')&&p.code!=='trial');if(found)setPlan(found);else setError('Choose a plan from your subscription page.');}).catch(e=>setError(e.message));},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;if(!plan||!token)return;setBusy(true);setError('');try{const result=await api<any>('/billing/checkout/demo',token,{method:'POST',body:JSON.stringify({planCode:plan.code,billingInterval:annual?'annual':'monthly'})});const billing=await api<any>('/billing/subscription',token);if(!result.activated||billing.subscription.status!=='active'||billing.subscription.plan_code!==plan.code)throw new Error('Subscription activation could not be confirmed. Refresh subscription status before trying again.');localStorage.setItem('relaywa_billing_updated',String(Date.now()));window.dispatchEvent(new Event('relaywa-billing-updated'));setReceipt(result);form.reset();}catch(e){setError(e instanceof Error?e.message:'Checkout failed.');}finally{setBusy(false);}}
 const amount=plan?(annual?plan.annual_price_cents:plan.monthly_price_cents)/100:0;
 return <main className="rw-checkout"><header><Brand/><Link href="/subscription">← Back to plans</Link></header><div className="rw-checkout-notice"><FeatherIcon name="shield"/> DEMO CHECKOUT · No charge · Use invented card details</div>{receipt?<section className="rw-checkout-success"><FeatherIcon name="check" size={40}/><h1>Purchase completed</h1><p>{plan?.name} · {annual?'Yearly':'Monthly'} · ${amount.toFixed(2)}</p><p>Your demo subscription is active. No payment was collected and no card information was saved.</p><p>Your {plan?.name} plan is now the current subscription. Trial restrictions have been replaced by its plan limits.</p>{receipt.invoice&&<DemoInvoice invoice={receipt.invoice}/>}<Link className="rw-button" href="/subscription">Return to subscription</Link></section>:<div className="rw-checkout-grid"><section className="rw-checkout-summary"><span className="rw-kicker">YOUR PLAN</span><h1>{plan?.name||'Checkout'}</h1><p>{annual?'Yearly':'Monthly'} subscription</p><div className="rw-checkout-amount">${amount.toFixed(2)}<small> / {annual?'year':'month'}</small></div><ul><li>{plan?.max_sessions} WhatsApp numbers</li><li>Session API credentials</li><li>Text, media and real-time webhooks</li></ul><hr/><div className="rw-checkout-total"><span>Total for this demo</span><strong>${amount.toFixed(2)}</strong></div><p className="rw-checkout-hint">This simulator activates your local plan and records a demo receipt. It does not renew or contact a payment provider.</p></section><section className="rw-checkout-form"><h2>Payment details</h2><p>Use any invented card details, or leave the fields blank. This completes a simulated purchase and activates your local plan.</p>{error&&<div className="rw-alert" role="alert">{error}</div>}{!token&&<p><Link href="/login">Sign in to continue</Link></p>}<form onSubmit={submit} autoComplete="off"><label>Cardholder name<input name="demo-name" placeholder="Alex Morgan" autoComplete="off"/></label><label>Card number<input inputMode="numeric" name="demo-number" placeholder="4242 4242 4242 4242" autoComplete="off" maxLength={30}/></label><div className="rw-checkout-fields"><label>Expiry<input name="demo-expiry" placeholder="MM / YY" autoComplete="off" maxLength={10}/></label><label>Security code<input name="demo-code" inputMode="numeric" placeholder="123" autoComplete="off" maxLength={6}/></label></div><button className="rw-button" disabled={busy||!plan||!token}>{busy?'Activating…':'Complete demo purchase'} <FeatherIcon name="right" size={14}/></button><small>Card fields stay in this page and are discarded after checkout.</small></form></section></div>}</main>;
}
