import Link from 'next/link';
import { SiJavascript, SiTypescript, SiPython, SiPhp, SiLaravel, SiNodedotjs, SiN8N } from 'react-icons/si';
import { FaJava, FaMicrosoft } from 'react-icons/fa6';
import { FeatherIcon as Icon, type FeatherName } from './feather-icon';

export const languageIcons = { JavaScript: SiJavascript, TypeScript: SiTypescript, Python: SiPython, PHP: SiPhp, Laravel: SiLaravel, 'C#': FaMicrosoft, Java: FaJava, 'Node.js': SiNodedotjs, n8n: SiN8N };
export function LanguageIcon({name}:{name:string}) { const Symbol=languageIcons[name as keyof typeof languageIcons];return Symbol?<Symbol className="rw-language-icon" aria-hidden="true"/>:<Icon name="code"/>; }
function Tile({icon,title,children}:{icon:FeatherName;title:string;children:React.ReactNode}){return <article className="rw-rich-tile"><span className="rw-icon-tile"><Icon name={icon} size={24}/></span><h3>{title}</h3><p>{children}</p></article>;}
export function DeveloperPlatforms(){return <section className="rw-site-section" id="integrations"><div className="rw-section-intro"><p className="rw-kicker">YOUR STACK, YOUR CHOICE</p><h2>Built to fit the tools<br/><em>you already use.</em></h2><p>A standard HTTP API works across languages. Keep your application architecture and add WhatsApp where it belongs.</p></div><div className="rw-platform-grid">{[
 ['Node.js','Use fetch in your Node.js service, then route incoming events to your application.', '/api-docs#integration-nodejs'],
 ['Python','Connect with requests or your preferred HTTP client. Build background jobs and event handlers.', '/api-docs#integration-python'],
 ['Laravel','Use Laravel’s HTTP client and queues to send notifications from your existing application.', '/api-docs#integration-laravel'],
 ['n8n','Configure a standard HTTP Request node. This is a manual recipe, not an official packaged RelayWA node.', '/api-docs#integration-n8n']
].map(([name,description,guideHref])=><article key={name}><span className="rw-platform-icon"><LanguageIcon name={name}/></span><h3>{name}</h3><p>{description}</p><Link href={guideHref}>Explore HTTP integration <Icon name="right" size={16}/></Link></article>)}</div><p className="rw-section-note">HTTP integration examples · published RelayWa SDK packages are not required.</p></section>;}
export function ConnectionSteps(){const steps=[
 {icon:'qr',title:'Connect your number',text:'Create a session and scan the QR code from WhatsApp’s Linked devices.',detail:'Your number, linked securely'},
 {icon:'key',title:'Copy your API key',text:'Your session key is created automatically after connection. Copy it to your application server.',detail:'One key for each session'},
 {icon:'send',title:'Send your first message',text:'Send messages through the API and receive customer replies through signed webhooks.',detail:'Messages out. Replies in.'}
];return <section className="rw-site-section rw-connect-section" id="how-it-works"><div className="rw-connect-heading"><div><p className="rw-kicker">HOW IT WORKS</p><h2>One number.<br/><em>Three simple steps.</em></h2></div><p>From your WhatsApp number to your first API message. A straightforward setup that fits your application.</p></div><ol className="rw-connect-steps">{steps.map((step,index)=><li className="rw-connect-card" key={step.title}><div className="rw-connect-card-top"><span className="rw-connect-icon"><Icon name={step.icon as FeatherName} size={23}/></span><span className="rw-connect-count">STEP 0{index+1}</span></div><h3>{step.title}</h3><p>{step.text}</p><div className="rw-connect-detail"><span aria-hidden="true"/>{step.detail}</div></li>)}</ol><div className="rw-connect-footer"><span>Ready when you are. Build at your own pace.</span><Link href="/api-docs">Follow the quickstart <Icon name="right" size={16}/></Link></div></section>;}
export function MessageFormats(){return <section className="rw-site-section rw-message-section" id="message-types"><div><p className="rw-kicker">MORE THAN A TEXT MESSAGE</p><h2>The right format<br/><em>for the conversation.</em></h2><p>Send the information your customer needs, and bring their replies back into your app through webhooks.</p><div className="rw-message-types">{[
 ['message','Text','Order updates, reminders and conversational replies.'],['image','Images & video','Share visual details through media endpoints.'],['document','Documents','Send invoices, reports and downloadable files.'],['voice','Audio','Send recordings and voice messages.'],['contact','Contacts','Share contact cards with the next person to reach.'],['location','Locations','Send coordinates for a pickup or meeting point.']
].map(([icon,title,text])=><Tile key={title} icon={icon as FeatherName} title={title}>{text}</Tile>)}</div><Link className="rw-button" href="/api-docs">See message endpoints <Icon name="right" size={16}/></Link></div><div className="rw-conversation" aria-label="Illustrative customer conversation"><header><span className="rw-icon-tile"><Icon name="message"/></span><div><strong>Repair desk</strong><small>Product illustration</small></div></header><div className="rw-chat-body"><div className="rw-chat-bubble">Hi, any update on my laptop repair?</div><div className="rw-chat-bubble outgoing">Your laptop is ready. We replaced the battery and completed the final checks.<small>Sent through your application</small></div><div className="rw-chat-bubble outgoing rw-chat-document"><Icon name="document" size={30}/><div><strong>Repair-report.pdf</strong><small>Document message</small></div></div><div className="rw-chat-bubble outgoing"><Icon name="location"/> Workshop location shared<small>Location message</small></div><div className="rw-chat-bubble">Great, I can collect it tomorrow morning.</div></div><footer><Icon name="events"/> Incoming reply → webhook → your app</footer></div></section>;}
export function UseCases(){return <section className="rw-site-section" id="use-cases"><div className="rw-section-intro"><p className="rw-kicker">MAKE IT PART OF YOUR PRODUCT</p><h2>Useful connections.<br/><em>Everyday possibilities.</em></h2><p>Your application decides what happens. RelayWa provides the messaging connection.</p></div><div className="rw-features">{[
 ['cart','Order & delivery updates','Connect your order workflow to confirmations, dispatch updates and collection messages.'],['bell','Appointment reminders','Send timely reminders and bring confirmations back into your scheduling system.'],['message','Customer support','Route incoming conversations to your support platform and respond from your own tools.'],['robot','AI-assisted conversations','Connect webhook events to your assistant, with your own review and escalation rules.'],['users','CRM workflows','Keep messaging activity alongside your existing contacts and customer records.'],['chart','Operations & reporting','Use message and session events to build the reporting your team needs.']
].map(([icon,title,text])=><Tile key={title} icon={icon as FeatherName} title={title}>{text}</Tile>)}</div></section>;}
export function InfrastructureSection(){return <section className="rw-site-section rw-infrastructure"><div><p className="rw-kicker">THE DETAILS THAT KEEP YOU IN CONTROL</p><h2>Every session has<br/><em>its own boundaries.</em></h2><p>Independent connection state and session credentials let you keep each number’s integration separate. Account tokens manage only the scopes you choose.</p><Link className="rw-button secondary" href="/api-docs">Understand the API <Icon name="right" size={16}/></Link></div><div className="rw-infrastructure-list"><Tile icon="layers" title="Isolated sessions">Inspect and operate individual numbers without sharing their credentials.</Tile><Tile icon="shield" title="Scoped access">Use session keys for messaging and account tokens for management. Revoke access when needed.</Tile><Tile icon="events" title="Signed event delivery">Verify webhook signatures, handle retries and connect events to your own workflows.</Tile></div></section>;}
